//! OpenAPI document for the Management API (served at `/api/v1/openapi.json`).
//!
//! Keep the `paths(...)` list in sync with every handler that carries a
//! `#[utoipa::path(...)]` attribute.

use utoipa::OpenApi;

use crate::autotune::{AutotuneReport, AutotuneRequest, AutotuneStep, KneeReason, WorkloadProfile};
use crate::model_health::{
    BulkModelHealthResult, UpdateModelHealthConfig, ValidateModelRequest, ValidateModelResult,
};
use crate::usage::{
    CacheStats, CostAgg, KeyUsageSummary, KeyUsageSummaryQuery, ModelUsageTimePoint,
    TenantUsageTimePoint, UsageAgg, UsageBreakdownQuery, UsageDailyQuery, UsageDailyRow,
    UsageKeyAgg, UsageKeyModelBreakdown, UsageLogQuery, UsageLogRow, UsageModelAgg, UsageQuery,
    UsageSeriesQuery, UsageTimePoint,
};
use crate::{
    AlertSettingsView, ApplyAutotuneCapacity, AuditEntryView, AuditQuery, AutoRouterSettingsView,
    BoonSettingsView, CapacityView, CharoSettingsView, CompactUsageResult, CompressorStatusView,
    CreateFairshareGroup, CreateKey, CreateMcpServer, CreateModel, CreateModelEndpoint,
    CreateTenant, CreatedKey, EmailSettingsView, EnergySettingsView, EnergyTestResult,
    FairshareHistoryPointView, FairshareHistoryQuery, FairshareHistoryView, FairshareLiveView,
    GroupFairshareView, KeyFairshareView, ListKeysQuery, LiveStats, McpServerView,
    ModelEndpointView, ModelPoolView, ModelRouteView, OverviewSummaryView, SetCapacity,
    SetDisabled, SetModelCache, SetModelCapacity, SetModelCapacityMode, SetModelReliability,
    SetModelWeight, SetTenantAllowlist, SetTenantBudget, SetTenantCompression, SetTenantGuardrails,
    SetTenantSchedule, SetTenantStatus, SetTenantSynthetic, TenantFairshareView, TestAlertResult,
    TestEnergyQuery, UpdateAlertSettings, UpdateAutoRouterSettings, UpdateBoonSettings,
    UpdateEmailSettings, UpdateEnergySettings, UpdateGroupWeight, UpdateKey, UpdateMcpServer,
    UpdateModel, UpdateModelEndpoint, UpdateQuota, UpdateTenant, UpdateTenantGroup,
    UpdateUsageRetention, UpdateWeight, UsageRetentionView,
};
use obleth_config::{
    ApiKey, ApiKeyBackup, AppSettingBackup, BackupData, BackupEncryption, CompressionPolicy,
    ConfigBackup, FairshareGroup, FairshareGroupBackup, GuardrailsPolicy, ManagedModelSpec,
    ManifestEndpoint, ManifestModel, McpServerBackup, ModelBackup, ModelEndpointBackup,
    ModelHealthCheck, ModelHealthDetail, ModelHealthSummary, ModelImportEntry, ModelImportReport,
    ModelManifest, ModelReplica, RestoreCounts, RestoreReport, Tenant, TenantBackup, WeeklyWindow,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "obleth Management API",
        description = "Programmatic control plane: tenants, keys, models, usage, fairshare, and settings."
    ),
    paths(
        // meta
        crate::get_version,
        crate::resync_resolver_cache,
        // tenants
        crate::create_tenant,
        crate::list_tenants,
        crate::get_tenant,
        crate::update_tenant,
        crate::delete_tenant,
        crate::patch_tenant_status,
        crate::patch_tenant_schedule,
        crate::patch_tenant_budget,
        crate::patch_tenant_allowlist,
        crate::patch_tenant_guardrails,
        crate::patch_tenant_compression,
        crate::set_tenant_synthetic_handler,
        crate::set_tenant_tracing_handler,
        crate::patch_weight,
        crate::put_quota,
        crate::patch_tenant_group,
        // keys
        crate::create_key,
        crate::list_keys,
        crate::update_key,
        crate::delete_key,
        crate::set_key_disabled,
        crate::set_key_tracing_handler,
        crate::get_key_usage,
        // usage & costs
        crate::get_usage,
        crate::get_usage_keys,
        crate::get_usage_keys_summary,
        crate::get_usage_models,
        crate::get_usage_series,
        crate::get_usage_series_tenants,
        crate::get_usage_series_models,
        crate::get_usage_breakdown,
        crate::get_cache_stats,
        crate::get_usage_logs,
        crate::get_request_spans,
        crate::get_usage_daily,
        crate::compact_usage,
        crate::get_costs,
        crate::get_stats,
        crate::get_overview_summary,
        // fairshare
        crate::get_fairshare_live,
        crate::get_fairshare_history,
        crate::list_fairshare_groups,
        crate::create_fairshare_group,
        crate::patch_fairshare_group_weight,
        // models
        crate::create_model,
        crate::list_models,
        crate::get_model,
        crate::update_model,
        crate::delete_model,
        crate::set_model_capacity,
        crate::set_model_capacity_mode,
        crate::autotune_model,
        crate::apply_autotune_capacity,
        crate::set_model_weight,
        crate::set_model_cache,
        crate::set_model_reliability,
        crate::knowledge::get_model_collections,
        crate::knowledge::set_model_collections,
        crate::list_model_endpoints,
        crate::create_model_endpoint,
        crate::update_model_endpoint,
        crate::delete_model_endpoint,
        // managed models & replicas
        crate::list_managed_models,
        crate::get_managed_model,
        crate::put_managed_model,
        crate::delete_managed_model,
        crate::set_provision_error,
        crate::list_replicas,
        crate::list_all_replicas,
        crate::create_replica,
        crate::patch_replica,
        crate::restart_replica,
        crate::delete_replica,
        crate::clear_lost_replicas,
        crate::model_health::list_health,
        crate::model_health::get_health,
        crate::model_health::check_one,
        crate::model_health::check_all,
        crate::model_health::update_config,
        crate::model_health::validate_model,
        // mcp
        crate::create_mcp_server,
        crate::list_mcp_servers,
        crate::get_mcp_server,
        crate::update_mcp_server,
        crate::delete_mcp_server,
        // audit & capacity
        crate::get_audit,
        crate::get_capacity,
        crate::set_capacity,
        // settings
        crate::get_alert_settings,
        crate::put_alert_settings,
        crate::test_alert_settings,
        crate::get_auto_router_settings,
        crate::router_readiness::get_router_readiness,
        crate::put_auto_router_settings,
        crate::simulate_route,
        crate::get_boon_settings,
        crate::put_boon_settings,
        crate::knowledge::get_knowledge_settings,
        crate::knowledge::put_knowledge_settings,
        // knowledge base
        crate::knowledge::list_collections,
        crate::knowledge::create_collection,
        crate::knowledge::get_collection,
        crate::knowledge::update_collection,
        crate::knowledge::delete_collection,
        crate::knowledge::list_documents,
        crate::knowledge::upload_document,
        crate::knowledge::delete_document,
        crate::knowledge::reindex_collection,
        crate::knowledge::reindex_document,
        crate::knowledge::search_collection,
        crate::get_energy_settings,
        crate::put_energy_settings,
        crate::test_energy_query,
        crate::get_compressor_status,
        crate::get_charo_settings,
        crate::put_charo_settings,
        crate::get_usage_retention,
        crate::put_usage_retention,
        crate::slurm_settings::get_slurm_settings,
        crate::slurm_settings::put_slurm_settings,
        crate::slurm_settings::test_slurm_settings,
        crate::slurm_settings::get_slurm_settings_resolved,
        crate::slurm_resources::get_slurm_resources,
        // recipes
        crate::recipes::list_recipes,
        crate::recipes::create_recipe,
        crate::recipes::update_recipe,
        crate::recipes::delete_recipe,
        // backup
        crate::backup::export_backup,
        crate::backup::restore_backup,
        // model manifest
        crate::models_io::export_models,
        crate::models_io::import_models,
    ),
    components(schemas(
        Tenant,
        ApiKey,
        FairshareGroup,
        ModelRouteView,
        ModelEndpointView,
        McpServerView,
        ModelHealthSummary,
        ModelHealthCheck,
        ModelHealthDetail,
        UpdateModelHealthConfig,
        BulkModelHealthResult,
        ValidateModelRequest,
        ValidateModelResult,
        CreateTenant,
        UpdateTenant,
        SetTenantStatus,
        SetTenantSynthetic,
        SetTenantSchedule,
        SetTenantBudget,
        SetTenantAllowlist,
        SetTenantGuardrails,
        GuardrailsPolicy,
        SetTenantCompression,
        CompressionPolicy,
        WeeklyWindow,
        UpdateWeight,
        UpdateQuota,
        UpdateTenantGroup,
        CreateFairshareGroup,
        UpdateGroupWeight,
        CreateKey,
        UpdateKey,
        CreatedKey,
        SetDisabled,
        ListKeysQuery,
        UsageQuery,
        UsageSeriesQuery,
        UsageDailyQuery,
        UsageLogQuery,
        KeyUsageSummaryQuery,
        UsageAgg,
        UsageKeyAgg,
        UsageModelAgg,
        KeyUsageSummary,
        UsageTimePoint,
        TenantUsageTimePoint,
        ModelUsageTimePoint,
        UsageBreakdownQuery,
        UsageKeyModelBreakdown,
        CacheStats,
        UsageLogRow,
        UsageDailyRow,
        CostAgg,
        LiveStats,
        OverviewSummaryView,
        FairshareLiveView,
        FairshareHistoryView,
        FairshareHistoryPointView,
        FairshareHistoryQuery,
        GroupFairshareView,
        TenantFairshareView,
        KeyFairshareView,
        ModelPoolView,
        CreateModel,
        UpdateModel,
        SetModelCapacity,
        SetModelCapacityMode,
        ApplyAutotuneCapacity,
        SetModelWeight,
        SetModelCache,
        SetModelReliability,
        CreateModelEndpoint,
        UpdateModelEndpoint,
        ManagedModelSpec,
        ModelReplica,
        crate::PutManagedModel,
        crate::CreateReplica,
        crate::PatchReplica,
        CreateMcpServer,
        UpdateMcpServer,
        AuditQuery,
        AuditEntryView,
        CapacityView,
        SetCapacity,
        UsageRetentionView,
        UpdateUsageRetention,
        CompactUsageResult,
        AlertSettingsView,
        EmailSettingsView,
        UpdateAlertSettings,
        UpdateEmailSettings,
        TestAlertResult,
        AutoRouterSettingsView,
        UpdateAutoRouterSettings,
        crate::SimulateRouteRequest,
        obleth_config::routing::route_explain::RouteExplain,
        obleth_config::routing::route_explain::ScoredCandidate,
        obleth_config::routing::route_explain::Rejection,
        obleth_config::routing::route_explain::WeightsView,
        obleth_config::routing::IntentSource,
        BoonSettingsView,
        UpdateBoonSettings,
        crate::knowledge::KnowledgeSettingsView,
        crate::knowledge::UpdateKnowledgeSettings,
        crate::knowledge::CollectionView,
        crate::knowledge::CreateCollection,
        crate::knowledge::UpdateCollection,
        crate::knowledge::DocumentView,
        crate::knowledge::UploadDocument,
        crate::knowledge::ReindexResult,
        crate::knowledge::SetModelCollections,
        crate::knowledge::ModelCollectionsView,
        EnergySettingsView,
        UpdateEnergySettings,
        TestEnergyQuery,
        EnergyTestResult,
        CompressorStatusView,
        CharoSettingsView,
        obleth_config::SlurmSettings,
        obleth_config::NodeAlias,
        crate::slurm_settings::SlurmSettingsView,
        crate::slurm_settings::UpdateSlurmSettings,
        crate::slurm_settings::SlurmHealthView,
        crate::slurm_settings::SlurmJwtHealth,
        crate::slurm_settings::SlurmPingHealth,
        crate::alerts::ChannelResult,
        AutotuneRequest,
        AutotuneReport,
        AutotuneStep,
        KneeReason,
        WorkloadProfile,
        ConfigBackup,
        BackupEncryption,
        BackupData,
        FairshareGroupBackup,
        TenantBackup,
        ApiKeyBackup,
        ModelBackup,
        ModelEndpointBackup,
        McpServerBackup,
        AppSettingBackup,
        RestoreReport,
        RestoreCounts,
        ModelManifest,
        ManifestModel,
        ManifestEndpoint,
        ModelImportReport,
        ModelImportEntry,
        crate::VersionInfo,
        crate::ResyncReport,
        crate::SetKeyTracing,
        crate::ProvisionErrorBody,
        crate::usage::SpanEntry,
        crate::recipes::RecipeView,
        crate::recipes::UpsertRecipeBody,
    )),
    tags(
        (name = "meta", description = "Gateway build/version identity and resolver-cache reconcile"),
        (name = "tenants", description = "Tenant lifecycle, quotas, and fairshare group assignment"),
        (name = "keys", description = "API key lifecycle and per-key usage summary"),
        (name = "usage", description = "Usage, cost, request logs, and live stats"),
        (name = "fairshare", description = "Live scheduler snapshot and group weights"),
        (name = "models", description = "Model registry, capacity, endpoints, health, and auto-tune"),
        (name = "mcp", description = "MCP server registry"),
        (name = "knowledge", description = "Institutional knowledge base: collections, documents, and re-indexing"),
        (name = "audit", description = "Admin audit log"),
        (name = "capacity", description = "Global gateway in-flight capacity"),
        (name = "settings", description = "Runtime alerting, auto-router, and retention configuration"),
        (name = "backup", description = "Configuration backup and restore"),
        (name = "slurm", description = "Live Slurm cluster resource discovery")
    )
)]
pub struct ApiDoc;

#[cfg(test)]
mod tests {
    use super::ApiDoc;
    use utoipa::OpenApi;

    #[test]
    fn model_route_view_documents_its_fields() {
        let doc = serde_json::to_value(ApiDoc::openapi()).expect("serialize");
        let props = &doc["components"]["schemas"]["ModelRouteView"]["properties"];
        for field in [
            "model_name",
            "aliases",
            "quantization",
            "route_bias",
            "auto_eligible",
        ] {
            let description = props[field]["description"].as_str().unwrap_or_default();
            assert!(
                !description.is_empty(),
                "ModelRouteView.{field} has no description"
            );
        }
    }
}
