//! OpenAPI document for the Management API (served at `/api/v1/openapi.json`).
//!
//! Keep the `paths(...)` list in sync with every handler that carries a
//! `#[utoipa::path(...)]` attribute.

use utoipa::OpenApi;

use crate::autotune::{AutotuneReport, AutotuneRequest, AutotuneStep, KneeReason, WorkloadProfile};
use crate::model_health::{BulkModelHealthResult, UpdateModelHealthConfig};
use crate::usage::{
    CacheStats, CostAgg, KeyUsageSummary, KeyUsageSummaryQuery, ModelUsageTimePoint,
    TenantUsageTimePoint, UsageAgg, UsageBreakdownQuery, UsageDailyQuery, UsageDailyRow,
    UsageKeyAgg, UsageKeyModelBreakdown, UsageLogQuery, UsageLogRow, UsageModelAgg, UsageQuery,
    UsageSeriesQuery, UsageTimePoint,
};
use crate::{
    AlertSettingsView, ApplyAutotuneCapacity, AuditEntryView, AuditQuery, AutoRouterSettingsView,
    BoonSettingsView, CapacityView, CharoSettingsView, CompactUsageResult, CompressorStatusView,
    CreateFairshareGroup, CreateKey, CreateMcpServer, CreateModel, CreateModelEndpoint,
    CreateTenant, CreatedKey, EmailSettingsView, EnergySettingsView, EnergyTestResult,
    FairshareLiveView, GroupFairshareView, ListKeysQuery, LiveStats, SetCapacity, SetDisabled,
    SetModelCache, SetModelCapacity, SetModelCapacityMode, SetModelReliability, SetModelWeight,
    SetTenantAllowlist, SetTenantBudget, SetTenantCompression, SetTenantGuardrails,
    SetTenantSchedule, SetTenantStatus, TenantFairshareView, TestAlertResult, TestEnergyQuery,
    UpdateAlertSettings, UpdateAutoRouterSettings, UpdateBoonSettings, UpdateEmailSettings,
    UpdateEnergySettings, UpdateGroupWeight, UpdateKey, UpdateMcpServer, UpdateModel,
    UpdateModelEndpoint, UpdateQuota, UpdateTenant, UpdateTenantGroup, UpdateUsageRetention,
    UpdateWeight, UsageRetentionView,
};
use obleth_config::{
    ApiKey, ApiKeyBackup, AppSettingBackup, BackupData, BackupEncryption, CompressionPolicy,
    ConfigBackup, FairshareGroup, FairshareGroupBackup, GuardrailsPolicy, ManagedModelSpec,
    McpServer, McpServerBackup, ModelBackup, ModelEndpoint, ModelEndpointBackup, ModelHealthCheck,
    ModelHealthDetail, ModelHealthSummary, ModelReplica, ModelRoute, RestoreCounts, RestoreReport,
    Tenant, TenantBackup, WeeklyWindow,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "obleth Management API",
        description = "Programmatic control plane: tenants, keys, models, usage, fairshare, and settings."
    ),
    paths(
        // meta
        crate::get_version,
        // tenants
        crate::create_tenant,
        crate::list_tenants,
        crate::get_tenant,
        crate::update_tenant,
        crate::delete_tenant,
        crate::patch_tenant_status,
        crate::patch_tenant_schedule,
        crate::patch_tenant_budget,
        crate::patch_tenant_allowlist,
        crate::patch_tenant_guardrails,
        crate::patch_tenant_compression,
        crate::patch_weight,
        crate::put_quota,
        crate::patch_tenant_group,
        // keys
        crate::create_key,
        crate::list_keys,
        crate::update_key,
        crate::delete_key,
        crate::set_key_disabled,
        crate::get_key_usage,
        // usage & costs
        crate::get_usage,
        crate::get_usage_keys,
        crate::get_usage_keys_summary,
        crate::get_usage_models,
        crate::get_usage_series,
        crate::get_usage_series_tenants,
        crate::get_usage_series_models,
        crate::get_usage_breakdown,
        crate::get_cache_stats,
        crate::get_usage_logs,
        crate::get_usage_daily,
        crate::compact_usage,
        crate::get_costs,
        crate::get_stats,
        // fairshare
        crate::get_fairshare_live,
        crate::list_fairshare_groups,
        crate::create_fairshare_group,
        crate::patch_fairshare_group_weight,
        // models
        crate::create_model,
        crate::list_models,
        crate::get_model,
        crate::update_model,
        crate::delete_model,
        crate::set_model_capacity,
        crate::set_model_capacity_mode,
        crate::autotune_model,
        crate::apply_autotune_capacity,
        crate::set_model_weight,
        crate::set_model_cache,
        crate::set_model_reliability,
        crate::list_model_endpoints,
        crate::create_model_endpoint,
        crate::update_model_endpoint,
        crate::delete_model_endpoint,
        // managed models & replicas
        crate::list_managed_models,
        crate::get_managed_model,
        crate::put_managed_model,
        crate::delete_managed_model,
        crate::list_replicas,
        crate::list_all_replicas,
        crate::create_replica,
        crate::patch_replica,
        crate::delete_replica,
        crate::clear_lost_replicas,
        crate::model_health::list_health,
        crate::model_health::get_health,
        crate::model_health::check_one,
        crate::model_health::check_all,
        crate::model_health::update_config,
        // mcp
        crate::create_mcp_server,
        crate::list_mcp_servers,
        crate::get_mcp_server,
        crate::update_mcp_server,
        crate::delete_mcp_server,
        // audit & capacity
        crate::get_audit,
        crate::get_capacity,
        crate::set_capacity,
        // settings
        crate::get_alert_settings,
        crate::put_alert_settings,
        crate::test_alert_settings,
        crate::get_auto_router_settings,
        crate::put_auto_router_settings,
        crate::get_boon_settings,
        crate::put_boon_settings,
        crate::get_energy_settings,
        crate::put_energy_settings,
        crate::test_energy_query,
        crate::get_compressor_status,
        crate::get_charo_settings,
        crate::put_charo_settings,
        crate::get_usage_retention,
        crate::put_usage_retention,
        crate::slurm_settings::get_slurm_settings,
        crate::slurm_settings::put_slurm_settings,
        crate::slurm_settings::test_slurm_settings,
        crate::slurm_settings::get_slurm_settings_resolved,
        crate::slurm_resources::get_slurm_resources,
        // recipes
        crate::recipes::list_recipes,
        crate::recipes::create_recipe,
        crate::recipes::update_recipe,
        crate::recipes::delete_recipe,
        // backup
        crate::backup::export_backup,
        crate::backup::restore_backup,
    ),
    components(schemas(
        Tenant,
        ApiKey,
        FairshareGroup,
        ModelRoute,
        ModelEndpoint,
        McpServer,
        ModelHealthSummary,
        ModelHealthCheck,
        ModelHealthDetail,
        UpdateModelHealthConfig,
        BulkModelHealthResult,
        CreateTenant,
        UpdateTenant,
        SetTenantStatus,
        SetTenantSchedule,
        SetTenantBudget,
        SetTenantAllowlist,
        SetTenantGuardrails,
        GuardrailsPolicy,
        SetTenantCompression,
        CompressionPolicy,
        WeeklyWindow,
        UpdateWeight,
        UpdateQuota,
        UpdateTenantGroup,
        CreateFairshareGroup,
        UpdateGroupWeight,
        CreateKey,
        UpdateKey,
        CreatedKey,
        SetDisabled,
        ListKeysQuery,
        UsageQuery,
        UsageSeriesQuery,
        UsageDailyQuery,
        UsageLogQuery,
        KeyUsageSummaryQuery,
        UsageAgg,
        UsageKeyAgg,
        UsageModelAgg,
        KeyUsageSummary,
        UsageTimePoint,
        TenantUsageTimePoint,
        ModelUsageTimePoint,
        UsageBreakdownQuery,
        UsageKeyModelBreakdown,
        CacheStats,
        UsageLogRow,
        UsageDailyRow,
        CostAgg,
        LiveStats,
        FairshareLiveView,
        GroupFairshareView,
        TenantFairshareView,
        CreateModel,
        UpdateModel,
        SetModelCapacity,
        SetModelCapacityMode,
        ApplyAutotuneCapacity,
        SetModelWeight,
        SetModelCache,
        SetModelReliability,
        CreateModelEndpoint,
        UpdateModelEndpoint,
        ManagedModelSpec,
        ModelReplica,
        crate::PutManagedModel,
        crate::CreateReplica,
        crate::PatchReplica,
        CreateMcpServer,
        UpdateMcpServer,
        AuditQuery,
        AuditEntryView,
        CapacityView,
        SetCapacity,
        UsageRetentionView,
        UpdateUsageRetention,
        CompactUsageResult,
        AlertSettingsView,
        EmailSettingsView,
        UpdateAlertSettings,
        UpdateEmailSettings,
        TestAlertResult,
        AutoRouterSettingsView,
        UpdateAutoRouterSettings,
        BoonSettingsView,
        UpdateBoonSettings,
        EnergySettingsView,
        UpdateEnergySettings,
        TestEnergyQuery,
        EnergyTestResult,
        CompressorStatusView,
        CharoSettingsView,
        obleth_config::SlurmSettings,
        crate::slurm_settings::SlurmSettingsView,
        crate::slurm_settings::UpdateSlurmSettings,
        crate::slurm_settings::SlurmHealthView,
        crate::slurm_settings::SlurmJwtHealth,
        crate::slurm_settings::SlurmPingHealth,
        crate::alerts::ChannelResult,
        AutotuneRequest,
        AutotuneReport,
        AutotuneStep,
        KneeReason,
        WorkloadProfile,
        ConfigBackup,
        BackupEncryption,
        BackupData,
        FairshareGroupBackup,
        TenantBackup,
        ApiKeyBackup,
        ModelBackup,
        ModelEndpointBackup,
        McpServerBackup,
        AppSettingBackup,
        RestoreReport,
        RestoreCounts,
        crate::VersionInfo,
        crate::recipes::RecipeView,
        crate::recipes::UpsertRecipeBody,
    )),
    tags(
        (name = "meta", description = "Gateway build/version identity"),
        (name = "tenants", description = "Tenant lifecycle, quotas, and fairshare group assignment"),
        (name = "keys", description = "API key lifecycle and per-key usage summary"),
        (name = "usage", description = "Usage, cost, request logs, and live stats"),
        (name = "fairshare", description = "Live scheduler snapshot and group weights"),
        (name = "models", description = "Model registry, capacity, endpoints, health, and auto-tune"),
        (name = "mcp", description = "MCP server registry"),
        (name = "audit", description = "Admin audit log"),
        (name = "capacity", description = "Global gateway in-flight capacity"),
        (name = "settings", description = "Runtime alerting, auto-router, and retention configuration"),
        (name = "backup", description = "Configuration backup and restore"),
        (name = "slurm", description = "Live Slurm cluster resource discovery")
    )
)]
pub struct ApiDoc;
