[package]
name = "obleth-provisioner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
obleth-config = { path = "../obleth-config" }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
